version: '3'
services:
  genmon:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TZ=America/Chicago
    volumes:
      - ./genmon:/config
    ports:
      - 8000:8000
    restart: unless-stopped
